In [1]:
# https://www.numpy.org/devdocs/user/quickstart.html
import numpy as np

# Ways to Create Array in Numpy

In [2]:
x1 = np.array([2,4,7,8,43,56,78,32,67])

In [3]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [4]:
x2 = np.array([i for i in range(1,100001) if i % 2 == 0])

In [5]:
len(x2)

50000

In [6]:
x2[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
x3 = np.arange(2,10001,2)

In [8]:
len(x3)

5000

In [9]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
# will return array of 50 numbers starting from 1.0 to 10.0
# x4 = np.linspace(1,10)

# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20, retstep=True)

In [11]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [12]:
np.random.rand(2,5,3)

array([[[0.7811263 , 0.41753776, 0.57721637],
        [0.60507758, 0.64537932, 0.27640688],
        [0.43103745, 0.24136633, 0.85729962],
        [0.08006401, 0.98070676, 0.27116902],
        [0.44750882, 0.42567827, 0.93593056]],

       [[0.88857799, 0.84723363, 0.62184928],
        [0.18189365, 0.90878954, 0.6129851 ],
        [0.52530601, 0.40224108, 0.22240717],
        [0.73415876, 0.49653604, 0.39445547],
        [0.85854704, 0.87017145, 0.00769127]]])

In [36]:
# will return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([30, 10, 44, 88, 61])

In [37]:
np.random.seed(5)
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [38]:
np.random.randint(10,100,5)

array([72, 37, 40, 90, 17])

In [15]:
np.random.rand()

0.08982103773760686

In [16]:
np.random.seed(5)

In [17]:
np.random.rand()

0.22199317108973948

In [18]:
np.random.random([5,5])

array([[0.87073231, 0.20671916, 0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 , 0.18772123, 0.08074127],
       [0.7384403 , 0.44130922, 0.15830987, 0.87993703, 0.27408646],
       [0.41423502, 0.29607993, 0.62878791, 0.57983781, 0.5999292 ],
       [0.26581912, 0.28468588, 0.25358821, 0.32756395, 0.1441643 ]])

# Methods of Numpy

In [19]:
x = np.random.randint(10,1000,200)

In [20]:
x.max()

997

In [21]:
x.min()

23

In [22]:
x.mean()

506.255

In [23]:
x.shape

(200,)

In [24]:
x.ndim

1

In [25]:
x.argmax()

157

In [26]:
x[154]

140

In [27]:
x.argmin()

97

In [28]:
x.argsort()[:10]

array([ 97,  37, 104, 197,  82, 192,  53,  54, 114,  69], dtype=int64)

# Slicing Numpy Array

In [29]:
x = np.array([[4,5,3,2],[6,8,3,6],[8,8,4,7]])

In [30]:
x

array([[4, 5, 3, 2],
       [6, 8, 3, 6],
       [8, 8, 4, 7]])

In [31]:
x.ndim

2

In [32]:
x.shape

(3, 4)

In [33]:
# in 2d data by default slicing will be row wise
x[0:2]

array([[4, 5, 3, 2],
       [6, 8, 3, 6]])

In [34]:
x[0:2, 0:2]

array([[4, 5],
       [6, 8]])

In [35]:
x[:,0:2]

array([[4, 5],
       [6, 8],
       [8, 8]])